### ISSUE TITLE
Point Star mode issue in Fisheye Mode

### ISSUE THREAD

**Issue by alcomposer** [CelestiaProject/Celestia#1156]
**Describe the bug**
When rendering in Fisheye mode, and stars are set to "point" mode, some stars (not all) turn into large squares.
This issue is not present on the same system when fisheye dome rendering is not activated.

**Screenshots**
![Screenshot from 2021-11-14 02-05-41](https://user-images.githubusercontent.com/12004932/141649798-cf7d2f32-9f6d-41d9-9915-be0c77b4a2b2.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Frontend: Qt
 - Version: Git Head
 - Graphics:
 ```
 Display: x11 server: X.Org 1.21.1.1 driver: loaded: nvidia resolution:
  1: 1920x1080~60Hz 2: 2560x1440~60Hz
  OpenGL: renderer: NVIDIA GeForce RTX 3090/PCIe/SSE2 v: 4.6.0 NVIDIA 495.44
```
NOTE:
I have also tested on macOS, Macbook Intel iGPU and have identical issue when using fisheye mode. What I have noticed is that the stars will render correctly when the application window is made smaller. Otherwise the stars that are large squares feel like they are possibly closer to the camera?

**Comment by levinli303** [comment]
this occurs because we draw stars with  GL_POINTS, and point size are capped. the sizes are calculated in shader... if we knew the size to render before passing it to render, then we can compare it with to the gl::maxPointSize and choose render as triangles instead. the way to resolve this now is just to change faintest star visible so stars are not that bright

**Comment by 375gnu** [comment]
@levinli303 the squares on the screenshot have different size. if your hypothesize is correct hey should be the same.

@alcomposer could you provide information shown in Help->OpenGL info?

**Comment by alcomposer** [comment]
Changing faintest stars (via [ ] ) does indeed fix this. However the fix is dependent on window size. If I resize the window larger then the large squares return.

I also need to look around and check that the faintest star setting is correct for all possible destinations, views.

Attached is the openGL info for my Nvidia Linux system. However I really doubt this is a driver bug, as it happens on the MacBook with Intel Graphics. 

@levinli303 is there a way to do min
max() on the point size? I don't know if the stars would look radically different given they are so far away anyway?

[Celestia_Nvidia_3090_4.6.0_NVIDIA_495.44.txt](https://github.com/CelestiaProject/Celestia/files/7543102/Celestia_Nvidia_3090_4.6.0_NVIDIA_495.44.txt)

**Comment by levinli303** [comment]
@375gnu I'm not sure why the sizes are different. But I did a repro here

With OpenGL, when I change the faintest visible, some squares become larger and some become smaller. This should not happen as they should all become either larger or smaller. maybe the max point size in GPU is not a hard limit at times and can be variable?
https://user-images.githubusercontent.com/17924287/141936384-24917839-27c9-41fc-9491-8a855a883601.mov

WIth ANGLE over Metal, the sizes are consistent capped to 64, this is because the translated shader code capped the size to 64.
https://user-images.githubusercontent.com/17924287/141936390-57d55028-3238-4de6-b4a9-0d145bae38b5.mov
