### ISSUE TITLE
Weird zooming out bug

### ISSUE THREAD

**Issue by Ezebytez** [CelestiaProject/Celestia#1284]
- [ ] When you zoom out really far it does this. Please fix https://user-images.githubusercontent.com/96560141/147693196-24e9e602-4f63-40c2-b203-14a65774bb7e.mp4

**Comment by Ezebytez** [comment]
Sorry for the bad quaility

**Comment by SevenSpheres** [comment]
This issue is present only on 1.7.0 (Windows/Qt/Android), not on 1.6.2. I'm able to replicate the change to a negative distance after zooming out very far; however, when returning to Earth, I see is an invisible Earth with a slightly flickery background, but not the "stretching" seen in the video. The same "stretching" issue was recently reported by nussun on the Discord server, though.

**Comment by Ezebytez** [comment]
Yeah there was a flickery background and stretching

**Comment by ajtribick** [comment]
Issue occurs when the conversion from `double` to `BigFix` when building a `UniversalCoord` out of an `Eigen::Vector3d` fails when the magnitude exceeds 2^63 microlightyears. Not sure why this triggers the warping of the viewport though, probably some of the parameters get out-of-sync with each other somewhere.

We should probably prevent the observer from moving further than a gigaparsec from the centre.
