### ISSUE TITLE
Phase angle value flickering

### ISSUE THREAD

**Issue by levinli303** [CelestiaProject/Celestia#1300]
**Describe the bug**
see the video, it seems only to happen when the value is zero. 

**Expected behavior**
No flickering between 0 and nan. just 0.

**Screenshots**

https://user-images.githubusercontent.com/17924287/147869398-a4125b5d-4ded-4683-ac9e-eb8533033e2a.mov

**Desktop (please complete the following information):**
 - OS: iOS/Android

**Comment by ajtribick** [comment]
I can't reproduce this behaviour on Windows desktop, but relevant lines of code are here: https://github.com/CelestiaProject/Celestia/blob/dea8c42eb1b8e931cb5530e380657e0cfe3246ca/src/celestia/celestiacore.cpp#L2961-L2965

We should allow for the possibility that numerical accuracy leads to the dot product calculation giving a value outside the valid range for `acos`:
```c++
double cosPhaseAngle = std::clamp(sunVec.dot(viewVec.normalized()), -1.0, 1.0);
```

but since I can't reproduce the issue, I'm not sure this will definitely fix it.

**Comment by levinli303** [comment]
> ```c++
> double cosPhaseAngle = std::clamp(sunVec.dot(viewVec.normalized()), -1.0, 1.0);
> ```


this indeed fixed it.

**Comment by 375gnu** [comment]
I wonder if the affected hardware supports `double` at all. And how many other places are affected by the similar issue.

**Comment by levinli303** [comment]
> I wonder if the affected hardware supports `double` at all. And how many other places are affected by the similar issue.

I can also reproduce on Mac/Windows(UWP)
