### ISSUE TITLE
The  nebulae never show up and they appear as non-exist objects.

### ISSUE THREAD

**Issue by bird0cosmic** [CelestiaProject/Celestia#1323]
**Describe the bug**
The bug is that nebulae never show up or appear non-existent.
**To Reproduce**
1. Go to 'go to object and type any nebulae name you can think of.'
2. Click on 'OK'
3. Scroll down to 'no need to scroll down'

**Expected behavior**
Nebulae are suppose to appear.
**Screenshots**
![Alcyone](https://user-images.githubusercontent.com/97418735/149607295-dce05ba4-3fec-4780-9cbc-5d376fe3beb5.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. GNU/Linux, Windows, mac OS]
 - Fronted: [e.g. Qt, native Win, native Mac]
 - Version: [e.g. 1.7.0]

**Additional context**

**Comment by SevenSpheres** [comment]
What nebula are you trying to go to? Alcyone is a star, not a nebula.

Keep in mind that nebulae are not included in default Celestia, but many are available as addons.

**Comment by SevenSpheres** [comment]
If the issue is just that you were expecting to see the blue nebulosity around the Pleiades, you can't see that in Celestia since no one has created an addon for it. If you want, you can read [this thread](https://celestia.space/forum/viewtopic.php?f=6&t=20299), which is about rendering nebulae in Celestia using sprites, and then try to create the Pleiades' nebula yourself.

**Comment by bird0cosmic** [comment]
It is fixed
