### ISSUE TITLE
Models display is broken since b7995997

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#1330]
**Describe the bug**
Commit b7995997:
![image](https://user-images.githubusercontent.com/1612688/150631195-3dbc733d-2c2f-4ff3-a2ce-196ff69376e7.png)

The previous one:
![image](https://user-images.githubusercontent.com/1612688/150631069-68878221-867e-4a0d-a4fa-eef4d45b20c0.png)

**Comment by SevenSpheres** [comment]
I'm not sure I see the issue here; is it the model's orientation?

**Comment by 375gnu** [comment]
No. 1) On the "bad" image the side of Hubble looking to the Sun is dark, it's darker than unlit side. 2) There is no shadows on it.

**Comment by 375gnu** [comment]
I've updated screenshots to the same URL: cel://Follow/Sol:Earth:Hubble/2022-01-22T08:31:15.66765Z?x=NThXWPz//////////////w&y=K1YIGwI&z=CELYeQY&ow=0.9525449&ox=0.16894078&oy=0.22911574&oz=-0.1078109&select=Sol:Earth:Hubble&fov=45.696148&ts=1.0&ltd=0&p=1&rf=203562899&nrf=224&lm=2048&tsrc=0&ver=3

**Comment by SevenSpheres** [comment]
> No. 1) On the "bad" image the side of Hubble looking to the Sun is dark, it's darker than unlit side. 2) There is no shadows on it.

Okay, I see the issue now; it's much clearer with the new images. This issue is not present on Windows.

**Comment by 375gnu** [comment]
it's present in windows builds as well. you sh'ld enable shadow maps to see it.

**Comment by SevenSpheres** [comment]
Ah yeah, I didn't have self-shadowing enabled (oddly, the option isn't is the current version of celestia.cfg; I had to copy it from an old version of that file I had). The issue still isn't present on the Qt frontend even with self-shadowing, though.

...although checking the native Windows frontend, spacecraft are completely invisible even without self-shadowing. Not sure if that's this issue or a different one, and Windows builds are failing so I can't check if the fix for this fixed that.
