### ISSUE TITLE
Cannot build on Linux

### ISSUE THREAD

**Issue by coder543** [CelestiaProject/Celestia#14]
All of the instructions insist that you just need to run 

```
./configure --with-gtk
make
make install
```

However, there is no `configure` file, only `configure.in`. Attempting to run `autoconf` fails with all kinds of errors, so I can't seem to generate the configure file myself.

**Comment by CelestiaProject** [comment]
Building for Linux has not tested yet. [Details about Celestia for Linux](https://en.wikibooks.org/wiki/Celestia/Development/Linux_platform#Basic_installation_steps).

**Comment by CelestiaProject** [comment]
@anordal Your changes intersect with the changes that we made this year. Your changes intersect with the changes that we made this year. Do your changes give a stable version of Celestia for Linux along with Lua 5.3?

**Comment by anordal** [comment]
Yes, Celestia runs fine here with Lua 5.3 on Linux as far as I can tell (dunno what lua specific issues to look for).

**Comment by CelestiaProject** [comment]
@anordal Please install Lua Edu Tools, check the correctness of its work and check several (any) CELX scripts.

**Comment by anordal** [comment]
That's some nice testing tips. I see the solution taken here (commit 0452b0aaeae) is to bundle Lua 5.1.

Note that my Lua 5.2 patch was made by Fedora maintainers back in 2013… So if you're saying that doesn't work, then *at least* the Fedora packages have been broken for years! I would assume other distros have applied equally desperate patches to keep it compiling in this decade.

I patched it for Lua 5.3 because my distro (OpenSuse Tumbleweed) doesn't make devel packages for Lua < 5.3 anymore – if you have to build Lua to build Celestia, that makes building Celestia twice as hard, which I (like you) refused to accept.

I hope we figure it out, but I don't know how cool those scripts are. I don't have time, and I'm a happy camper even if I broke them.

**Comment by CelestiaProject** [comment]
@anordal Do you have full Celestia source code with Lua 5.2 or 5.3? We would like to get it to build for Windows for testing CELX scripts and LUA tools.

**Comment by anordal** [comment]
> full Celestia source code

Only what I cloned myself, I haven't tried upgrading Lua in this project (yet).

**Comment by scottmmjackson** [comment]
4e947ef387b554c68fc32da95a2a2bcdee3e1f78 is the closest I can get to the last commit that actually builds on Linux:

Dependency instructions are deb/ubuntu specific but the rest should be roughly platform-independent
```
sudo apt install libgtk2.0-dev libgtkglext1-dev liblua5.1-0-dev freeglut3-dev
git clone https://github.com/CelestiaProject/Celestia
cd Celestia
git checkout 4e947ef387b554c68fc32da95a2a2bcdee3e1f78
autoreconf -iv
./configure --with-gtk
make
vim po/Makefile # set mkdir_p var at the top to "mkdir -p"
vim po2/Makefile # same
sudo make install
```

HTH

The most recent commit is broken and impossible to build. It apparently uses some proprietary windows-only `fmod` library without wrapping it in an `#ifdef _WIN32_` block, so it simply will not build on Linux. It's been this way since about March.

**Comment by CelestiaProject** [comment]
Closed due to inactivity.

**Comment by scottmmjackson** [comment]
Is support for Linux being dropped, then?

**Comment by anordal** [comment]
I'll keep my fork building anyway.

**Comment by munix9** [comment]
fyi:
qt5 builds (git main) for current openSUSE distros on obs
https://build.opensuse.org/package/show/home:munix9/celestia
https://software.opensuse.org//download.html?project=home:munix9&package=celestia
ciao

**Comment by anordal** [comment]
@munix9 Thanks, it works! My favourite distro. And qt5, wow! 🥇 

Mouse interaction is very buggy in Xwayland though (unusable if the window is extended over two screens), but that might very well be a qt's fault – my very stripped down version works fine.

**Comment by nortikin** [comment]
make 
make: *** has not defined aims

how to make?

**Comment by nortikin** [comment]
ok
configure: error: No glut.h found. See INSTALL file for help.

**Comment by nortikin** [comment]
ok.
bunch of issues in terminal in make, followed all recomendations https://github.com/CelestiaProject/Celestia/issues/14#issuecomment-301240090 here and https://github.com/CelestiaProject/Celestia/issues/14#issuecomment-326426389 there
```bash
xBase<OtherDerived>&) [with OtherDerived = Eigen::Product<const Eigen::Matrix<float, 4, 4>&, const Eigen::Matrix<float, 4, 4>&, 0>; _Scalar = float; int _Rows = 4; int _Cols = 4; int _Options = 2; int _MaxRows = 4; int _MaxCols = 4]’
../../thirdparty/Eigen/Eigen/src/Core/Product.h:204:30:   required from ‘Eigen::Product<Lhs, Rhs, ProductMode>::Product(const Lhs&, const Rhs&) [with Lhs = Eigen::Product<const Eigen::Matrix<float, 4, 4>&, const Eigen::Matrix<float, 4, 4>&, 0>; Rhs = Eigen::Matrix<float, 4, 4>; LhsNested = Eigen::Matrix<float, 4, 4>; RhsNested = const Eigen::Matrix<float, 4, 4>&; int ProductMode = 0]’
../../thirdparty/Eigen/Eigen/src/Core/Product.h:298:60:   required from ‘const typename Eigen::ProductReturnType<Derived, OtherDerived>::Type Eigen::MatrixBase<Derived>::operator*(const Eigen::MatrixBase<OtherDerived>&) const [with OtherDerived = Eigen::Matrix<float, 4, 4>; Derived = Eigen::Product<const Eigen::Matrix<float, 4, 4>&, const Eigen::Matrix<float, 4, 4>&, 0>; typename Eigen::ProductReturnType<Derived, OtherDerived>::Type = Eigen::Product<Eigen::Matrix<float, 4, 4>, const Eigen::Matrix<float, 4, 4>&, 0>]’
shadermanager.cpp:3419:92:   required from here
../../thirdparty/Eigen/Eigen/src/Core/Product.h:260:14: warning: ignoring attributes on template argument ‘Eigen::MatrixBase<Eigen::Product<const Eigen::Matrix<float, 4, 4>&, const Eigen::Matrix<float, 4, 4>&, 0> >::PacketScalar {aka __vector(4) float}’ [-Wignored-attributes]

```

**Comment by nortikin** [comment]
i hope it will install...

**Comment by nortikin** [comment]
ok, it works!!!!
