### ISSUE TITLE
Spelling problem in Qt

### ISSUE THREAD

**Issue by TheLostProbe** [CelestiaProject/Celestia#1464]
when right-clicking on an object in the celestial browser, the "sync orbit" option in the right-click submenu is spelled as "synch orbit". both spellings are correct, but it should be standardized. ideally use the "sync" spelling instead of "synch", because the "synch" spelling is _very_ rarely used

**To Reproduce**
1. open the celestial browser
2. right click on an object in the list, doesnt have to be any one in particular
3. see error

**Expected behavior**
"synch orbit" should be "sync orbit" as it is more commonly used

**Screenshots**
![image](https://user-images.githubusercontent.com/67564416/206095394-b00bab7f-a016-4908-8a48-3c3ecb158e1b.png)

**Desktop**
 - OS: Windows 10 Home 21H2 build 19044.2251
 - Frontend: Qt
 - Version: 1.7.0, latest `master` build

UPDATE: this also shows up in the right-click menu that pops up when right-clicking on a planet

**Comment by dave-kaye** [comment]
@ajtribick deleted their fix for this issue due to concerns with translations.  I have looked through all the po/*.po files and none of them have a "synch" entry, only "sync" from celestiacore.cpp.  I do not see any other translations area, specifically a qt code version that uses qt translation program.

Therefore, @375gnu should be able to mark this issue as closed.

**Comment by ajtribick** [comment]
@dave-kaye - the po file contains `S&ynch Orbit` because the source string includes the shortcut key. The issue I ran into is that the translation files *also* have "S&ync Orbit" from winmain.cpp, and some languages have this translated differently.

E.g. from "ro.po"

Qt: "Orbită s&incronizată"
https://github.com/CelestiaProject/Celestia/blob/c722b7d8f984b05508aa7d5771b356da99927f12/po/ro.po#L2611-L2613

Windows: "&Orbită sincronă"
https://github.com/CelestiaProject/Celestia/blob/c722b7d8f984b05508aa7d5771b356da99927f12/po/ro.po#L4144-L4146

(note that in this case, the shortcut key is also different: i on Qt, but O on Windows)

**Comment by 375gnu** [comment]
Let's leave this to translators

**Comment by dave-kaye** [comment]
@ajtribick Thank You for pointing out my error.  When I searched the source code I used "sync" "synch"  "ync" and "orbit" to try to guarantee that I found all synch listings.  But I didn't do that in the po files.  I do see your issue.  Moreover, sync is also in celestiacore.cpp - usually with an even different translation than win and qt.

It is a problem for the translators to sort out.  As the interface is slightly evolving, at some time the master .pot file will have to be updated and perhaps they can address it then.  I don't know if there is a problem list for the translators, but if there is then this should be noted on it.

Thanks.
