### ISSUE TITLE
Weird mouse drag behaviour with Qt on Wayland

### ISSUE THREAD

**Issue by Askaniy** [CelestiaProject/Celestia#1489]
**Describe the bug**
The actions of camera rotation and target rotation are nearly impossible due to the unexpected reaction. Apparently, the direction of rotation is calculated by averaging the direction over the entire time the mouse button is held down.

This is most likely caused by my too modern configuration. Just installed the program from the [repository for openSUSE](https://download.opensuse.org/repositories/home:/munix9:/unstable/openSUSE_Tumbleweed/).
Note: There is another cursor actions bug that is seen on all devices: #1344 

**Configuration**
 - OS: GNU/Linux, openSUSE Tumbleweed 20221229
 - Desktop environment: KDE Plasma 5.26.4 + _Wayland_
 - Frontend: Qt
 - Version: 1.7.0 c722b7d
 - CPU: AMD Ryzen 5 5600G (x64), Radeon Graphics

**Comment by ajtribick** [comment]
I can reproduce something which sounds similar: occurs when I launch from a Wayland session but works fine under X11.

**Comment by ajtribick** [comment]
The immediate cause of this is fairly straightforward: Wayland does not support warping the cursor, so the call to `QCursor::setPos` in the mouse event handlers fails. This then makes the delta calculations wrong and hence the strange cursor behaviour.

A simple partial fix would be to update the saved local position with the current local position on platforms, except on platforms that support pointer warping (which I assume is at least `cocoa`, `windows`, and `xcb` - see the [documentation of `QGuiApplication::platformName()`](https://doc.qt.io/qt-5/qguiapplication.html#platformName-prop)). This is a partial fix because it would limit the drag distance to the desktop boundaries.

Wayland does support locking the pointer and getting relative mouse motion events via the [pointer constraints protocol](https://wayland.app/protocols/pointer-constraints-unstable-v1) but Qt does not provide an equivalent to this API so would require writing Wayland code directly.

**Comment by Askaniy** [comment]
Just tested, #1507 fixes it 👍
