### ISSUE TITLE
[Windows] The thickness of the XYZV orbital lines varies with distance

### ISSUE THREAD

**Issue by Lepestronik** [CelestiaProject/Celestia#1629]
**Describe the bug**
When moving away from an object with a sampled trajectory, the thickness of its orbit increases.

**To Reproduce**
It can be reproduced on spacecraft with XYZV trajectories from version 1.7.0 (for example, "Cassini").

**Expected behavior**
Thin orbital lines that do not change the thickness when the distance changes (like Keplerian orbits behave).

**Screenshots**
![Orbits thickness](https://user-images.githubusercontent.com/89343875/223707891-c5271416-63ff-4d4b-9025-2c59dd750dc8.png)

**Desktop:**
 - OS: Windows 10 and 11.
 - Frontend: native Win and Qt (Qt was not tested on Windows 11 because it could not be started there).
 - Version: 1.7.0.
 
**Additional context**
According to observations, it seems that as the thickness of the orbits increases, the load on the system increases.

**Comment by Lepestronik** [comment]
Additional info: this effect disappears when anti-aliasing is disabled in the settings. On Linux both options look fine.

**Comment by 375gnu** [comment]
@Lepestronik are you sure that the issue is caused by the distance? On your screenshots orbits have different shapes and the first one is very close to a straight line tilted ~45 deg, so the second case requires much more pixels to render (try the same on a sheet of paper with cells).

So I believe this issue is about windows GL drivers rather than about Celestia.

**Comment by 375gnu** [comment]
closing as there is no response
