### ISSUE TITLE
Updates to processing RA/Dec/Distance for stars

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1678]
The handling of RA/Dec/Distance in .stc files currently does the following:

https://github.com/CelestiaProject/Celestia/blob/b6628c7d19d0d57a5c6ced2aeb8804c86adb6034/src/celengine/stardb.cpp#L957-L967

The justification given there ("to match behavior of reading from binary file") appears to be a legacy of when stars.dat stored RA/Dec/Distance values instead of Cartesian coordinates. I think it should therefore be possible to replace the code with:

```cpp
if (modifyPosition)
{
    Eigen::Vector3d pos = astro::equatorialToCelestialCart(ra, dec, distance);
    star->setPosition(pos.cast<float>());
}
```

This would be a better match to the behavior of the DSO loader, which does not truncate coordinates to single precision (including Cartesians), and probably have advantages for extragalactic star positioning. On the other hand it would result in slight changes to add-on behavior, which might result in cel URLs becoming outdated.

Thoughts?

**Comment by 375gnu** [comment]
We can find out if we actually break something only if we break it. So my proposal is to add `#if` guards and use the proposed change by default. Keep the old code disabled for ~ 1 year. If there're reports on broken stuff we can disable the new code and enable the old one back if we consider these reports important (e.g. there're a lot of them or breakage is significant). Otherwise we remove the old code.
