### ISSUE TITLE
Inconsistency of  menu item title of shortcuts for split view

### ISSUE THREAD

**Issue by levinli303** [CelestiaProject/Celestia#1766]
https://github.com/CelestiaProject/Celestia/blob/062d5b254a5ee8bacb7cc71a36fb6aa1950d09b9/controls.txt#L123 https://github.com/CelestiaProject/Celestia/blob/062d5b254a5ee8bacb7cc71a36fb6aa1950d09b9/ChangeLog#L640 suggest that 
CTRL + U -> Horizontal split (left and right)
CTRL + R -> Vertical split (top and bottom)

however in code implementation it seems frontends are using the reversed versions
https://github.com/CelestiaProject/Celestia/blob/062d5b254a5ee8bacb7cc71a36fb6aa1950d09b9/src/celestia/gtk/ui.h#L74 https://github.com/CelestiaProject/Celestia/blob/062d5b254a5ee8bacb7cc71a36fb6aa1950d09b9/src/celestia/win32/res/celestia.rc#L245 https://github.com/CelestiaProject/Celestia/blob/062d5b254a5ee8bacb7cc71a36fb6aa1950d09b9/src/celestia/qt/qtappwin.cpp#L841

Pressing CTRL + U still split window horizontally in behavior, but the associated menu item has the title "Split vertically"

**Comment by 375gnu** [comment]
Qt behaves properly.

**Comment by levinli303** [comment]
> Qt behaves properly.

The horizontal split QAction is associated with Ctrl+U shortcut

```
 QAction* splitViewHorizAction = new QAction(QIcon(":/icons/split-horiz.png"),
                                                _("Split view horizontally"), this);
 splitViewHorizAction->setShortcut(QString(_("Ctrl+U")));
connect(splitViewHorizAction, SIGNAL(triggered()), this, SLOT(slotSplitViewHorizontally()));
multiviewMenu->addAction(splitViewHorizAction);
```

But the slot method calls `charEnter` with CTRL + R

```
void CelestiaAppWindow::slotSplitViewHorizontally()
{
    m_appCore->charEntered('\022');
}
```

**Comment by dave-kaye** [comment]
I have tested the split view function on the Celestia user interfaces that are presently operational.  I found that there is no consistency between interfaces; either in definition of the split, the icons, the hot keys or the actual window response.

The table below is the information the menu bar (toolbar) displays. The column names vertical and horizontal are the menu item descriptions (in words) found on the menu bar for the Celestia interface type listed. The menu icon is the picture that is alongside of the menu item. The hot key is the shortcut key listed on the menu item.  For reference, the shortcut keys listed in the Help Guide and controls.txt file (both of which can be displayed in the Help area) are also given. Several interfaces do not have icons, and the SDL and Glut interfaces have no menu - they are keyboard driven.

![toolbar](https://github.com/CelestiaProject/Celestia/assets/91984396/8bd45430-2a75-4289-85fd-36248bec8e93)

When the menu item was clicked, the action response of the window is diagrammed below in the first columns. When the hot key indicated was entered, the response of the window is diagrammed below in the last columns.

![response](https://github.com/CelestiaProject/Celestia/assets/91984396/bfa12eae-9a42-483c-978f-7fe0b2ade735)

DISCUSSION:

First, the definition of a vertical and horizontal split must be agreed upon. From the window response to the menu items, most of the graphical user interfaces have the same definition. Only the KDE3 interface switches the definitions. KDE3 interface is available in the Celelstia 1.6.x series, but is being phased out and few Linux distributions support KDE3. Therefore, using the response of the majority of the new Celestia versions, the proposed definitions are:

- Vertical Split - Split line in the vertical direction to create a left and right window pane.

- Horizontal Split - Split line in the horizontal direction to create a top and bottom window pane.

So the definitions in picture form are:

![definition](https://github.com/CelestiaProject/Celestia/assets/91984396/90ad17ff-9320-453a-a4d6-51117f05fc69)

This leads to menu icon styles as:

![menu icons](https://github.com/CelestiaProject/Celestia/assets/91984396/6b7f8d3b-1619-4f8f-9316-fbe68377caf5)

Using these definitions, the response of the KDE3 interface should be changed - switching the responses when selecting the items on the menu bar (toolbar). However, the response and icons displayed on the menu do agree. Since the KDE3 interface is being abandoned, it is not mandatory to change the code - users can readily see what the menu item action is. All other Celestia interfaces would not need to be changed. They are consistent in menu item action.

Continuing to utilize these definitions, the actions of the hot keys (shortcut keys) can be examined. Review the window response table at the hot key columns. All of the present interfaces except one show a horizontal split when the `<Ctrl> + R` key combination is entered and a vertical split when the `<Ctrl> + U` key combination is entered. The outlier is the Qt 1.7.0 interface series; where the actions are reversed. The actions called when the hot key combination is entered should be switched for the Qt interface. Then all interfaces will utilize the same hot key combination for the same action response.

While the actions of the hot keys are nearly uniform across the interfaces, the user information is not. Looking at the table tool bar display-section hot key columns shows an even split. Using the previous decisions, the vertical hot key column should all read `<Ctrl> +  U`. This means that the words in the menu should be changed to "Split view vertically   Ctrl+U" and "Split view horizontally  Ctrl+R" for the Qt and KDE3 interfaces. This is only the words displayed by the interface menu item, no other coding needs to be changed for this section. In addition, the Help Guide and controls.txt files should have two lines changed. The suggested lines would read "_Ctrl+U  Split view vertically into left and right views_" and "_Ctrl+R  Split view horizontally into top and bottom views_". The additional description in the lines would prevent confusion in the future.
 
 Finally, the menu icons displayed can be examined. With the exception of the KDE3 interface, all current interfaces that show menu icons are consistent with the previous discussion and no action is required.
 
 SUGGESTED ACTION SUMMARY:
 

1. Ignore KDE3 interface unless the code changes are so minor as to be trivial to implement
2. Switch the hot key actions on the Qt interface
3. Switch the hot key words on the menu item description for the Qt interface
4. Modify the hot key lines for the Help Guide and controls.txt file

 These actions would create a uniform display and event action across all interfaces. It should be noted that this does not include the macOS interface, I have no access to this interface and others would have to look at this. It also should be noted that there is a great number of user manuals and guides on the internet that probably have multiple versions of this information that can be wrong.

**Comment by dave-kaye** [comment]
After reviewing the source code for the interfaces, core modules and scripting languages, the internal naming structure within the code is consistent. It is always a version of the following: HorizontalSplit which means the view window is split in the horizontal direction into upper and lower sections. VerticalSplit which means the view window is split in the vertical direction into left and right sections.

The user interfaces which have menu items (win32, gtk and qt) all have items stating "split view vertically" or "split view horizontally" which match the definitions in the code as stated above. If the menu item has an icon, it matches the definition.

The shortcut key `<Ctrl>+R` is associated with the split horizontally function. The shortcut key `<Ctrl>+U` is associated with the split vertically function.  The keys match the menu items (when available) and code definitions/functions given above in the win32, gtk, sdl and glut interfaces.  The keys are reversed in the Qt interface, both on the menu items and functionality.

KDE3 uses a different definition for the split, where horizontal creates side by side views, and vertical creates upper and lower views. These are seen in the menu items. But the control keys give the same window split structure as discussed above.

The controls.txt file and help file link the control keys to the words horizontal and vertical. However, they are using the definition horizontal creates side by side views, and vertical creates upper and lower views.

To create a uniform interface, the definitions should be:

    Vertical Split - Split line in the vertical direction to create a left and right window pane.

    Horizontal Split - Split line in the horizontal direction to create an upper and lower window pane.
    
These definitions will match all the user menu items and the internal definitions of the code.

Then:

- Switch the shortcut keys for the Qt interface. All the interfaces will get the same response from the same shortcut keys.

- Switch the vertical/horizontal labels for the shortcut keys in the controls.txt file and help file, plus add verbiage to more clearly state what the end result of the key is.

- Ignore the KDE3 interface, as it is being discontinued and KDE3 based systems are not easily available.  It will remain an outlier to the other interfaces, but it is internally consistent so the user should not have a problem.

The overall issue is the definition of horizontal and vertical.  In most of the areas, it refers to the direction of the split, so a horizontal split will create an upper and lower section. In some cases it refers to the result of the split, so horizontal will have two windows side by side in a horizontal manner.  If the issue remains or causes confusion, the easiest solution is to change the wording of the menu items from "split view horizontally" to "split into upper/lower sections" and "split view vertically" to "split into left/right sections".

**Comment by dave-kaye** [comment]
I think the commit closes this issue.
Please check.

**Comment by 375gnu** [comment]
@dave-kaye in your PR description you can add `Closes: #NNN` where NNN is the issue number and will be closed automatically.
