### ISSUE TITLE
GUI style on Qt6 frontend is not the expected one

### ISSUE THREAD

**Issue by Askaniy** [CelestiaProject/Celestia#1884]
Opened both Qt5 and Qt6 on the 7f97b84, the Qt6 one seems using wrong design templates.

**Expected behavior**
Last time I checked, Qt6 was closer to Qt5 with more material design, not skeuomorphic.

**Screenshots**
![image](https://github.com/CelestiaProject/Celestia/assets/44873271/eb351328-ebd5-495f-a7d5-2aa6346c3309)

**Desktop:**
 - OS: Linux, openSUSE Tumbleweed, KDE
 - Frontend: Qt
 - Version: 1.7.0

Also, there's minux9's builds space formatting mismatch:
![image](https://github.com/CelestiaProject/Celestia/assets/44873271/f47406a4-e5dd-4931-95c5-8f6cb8a72a33)

**Comment by munix9** [comment]
> Opened both Qt5 and Qt6 on the [7f97b84](https://github.com/CelestiaProject/Celestia/commit/7f97b84c0dcba8ce5618079082711df8e5f30b9e), the Qt6 one seems using wrong design templates.
> 
> **Expected behavior** Last time I checked, Qt6 was closer to Qt5 with more material design, not skeuomorphic.
> 

Quite possible. Keep in mind that Tumbleweed is a rolling release and versions of components and libraries and even the appearance can (and will) change from time to time.
Due to the fact that often current software is rolled out, it can also come to problems in the meantime, also in the graphical output or display.

If you need a more stable base and want to use openSUSE, you should better use Leap 15.4/15.5 (current) (although Tumbleweed is very stable and has been my favorite for years).

Otherwise, please define more precisely what is meant by "feel".

> 
> Also, there's minux9's builds space formatting mismatch:

Hm, I can do nothing with it. Where should the space be?
In my KDE menu search, both entries appear correctly with Qt5 and Qt6 (without a space).

In fact, I think it should be "Qt 5" and "Qt 6" all the way through, at least that's how it shows up on the homepage:
https://www.qt.io/product/qt6

**Comment by Askaniy** [comment]
> Otherwise, please define more precisely what is meant by "feel".

Yeah, it was defined in "Expected behavior" section.

If it's most likely that the problem is on my (Tumbleweed) side, I'll close the issue. I opened it in case the behavior is repeated on other systems and suggest waiting for a couple more people to check.

**Comment by ajtribick** [comment]
We don't actually do anything with setting themes in the Qt front-ends (there is one call to `setStyleSheet` that enables scrollable menus in the selection popups, and we use `QStyle` to retrieve the directory icon), so the Qt5/Qt6 theme differences aren't related to the Celestia code.
