### ISSUE TITLE
Flatpak/Flathub build

### ISSUE THREAD

**Issue by faveoled** [CelestiaProject/Celestia#2049]
Hello,

Could you publish your application to [Flathub](https://flathub.org/)? It's based on a cross-distro [Flatpak technology](https://docs.flatpak.org/en/latest/introduction.html).

Or: would you agree if someone else writes the necessary build files for you and sends them to the Flathub maintainers?

**Comment by 375gnu** [comment]
@faveoled please check https://github.com/CelestiaProject/Celestia/discussions/1988, Flatpaks are provided by Fedora community.

**Comment by faveoled** [comment]
@375gnu Thanks, didn't know about that. But what about Flathub submission?

**Comment by 375gnu** [comment]
We don't have human resources to maintain additional packaging. If want to volunteer we'll be grateful.

**Comment by ColinKinloch** [comment]
I've created a manifest for Celestia and a PR to get it on flathub: https://github.com/flathub/flathub/pull/4955
@375gnu is this okay with you?
Currently it uses cmake which looks like isn't in a stable release yet.

**Comment by 375gnu** [comment]
I'm fine with this. @ajtribick @levinli303 any objections from your side?

**Comment by levinli303** [comment]
looks good to me.

**Comment by RacerBG** [comment]
I don't want to open a new issue about this so I will write it here:

After trying to test the flatpak build (GTK, Qt and SDL) I was always getting a CTD, Celestia didn't even started. The problem was related to my locale settings:
`Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8. Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead. If this causes problems, reconfigure your locale. See the locale(1) manual for more information.`

The output of localectl is:
`System Locale: LANG=en_US.UTF-8
LANGUAGE=en_US:en
VC Keymap: (unset)
X11 Layout: us,bg
X11 Model: pc105
X11 Variant: ,phonetic
X11 Options: grp:alt_shift_toggle,grp_led:scroll`

And locale shows:
`LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=bg_BG.UTF-8
LC_TIME=bg_BG.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=bg_BG.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=bg_BG.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=`

The problem was fixed by adding the following variable: `--env=LC_ALL=C.UTF-8` which was suggested by @ColinKinloch 

This problem never happened before. I have 78 flatpaks and Celestia is the first one where I need to use such workarounds. This leads me to believe that the problem is probably not caused by the flatpak build.

What could be a proper solution for this?

Thanks in advance!

**Comment by ajtribick** [comment]
We don't maintain the Flatpak.

**Comment by RacerBG** [comment]
> We don't maintain the Flatpak.

I know that. I'm asking if the locale error is relevant to Celestia in any way.

**Comment by ajtribick** [comment]
A quick search of Flatpak and locales suggests that there have been numerous issues regarding Flatpak and mixed locales, e.g. https://github.com/flatpak/flatpak/issues/3712. Since your locale output indicates a mixture of English and Bulgarian locales, maybe this is causing issues.

**Comment by RacerBG** [comment]
> A quick search of Flatpak and locales suggests that there have been numerous issues regarding Flatpak and mixed locales, e.g. [flatpak/flatpak#3712](https://github.com/flatpak/flatpak/issues/3712). Since your locale output indicates a mixture of English and Bulgarian locales, maybe this is causing issues.

Thanks for pointing that out! Well, that was the answer I needed, sorry to bother you and thanks about your commitment to Celestia. :smiley:

**Comment by RacerBG** [comment]
Actually it was my fault. After creating `/etc/locale.conf`  the issue solved itself. Even changing the language with the variable `LANGUAGE` works too.
