### ISSUE TITLE
Suggestion: change files structure or change STATIC library to OBJECT

### ISSUE THREAD

**Issue by dlshcbmuipmam** [CelestiaProject/Celestia#352]
Currently, the sub-libraries of Celestia are quite chaotic. For example, celestia depends on celengine, and celengine depends on celestia. This dependencies are not stated clearly in the cmake files - there are some missing libraries in the target_link_libraries. 

This is the reason why shared libraries can't be built, and it is harmful for people (like me :) ) to understand the programming logic. Therefore I have the following suggestions:

1. If the libraries are important for Celestia design, should we re-order the files such that there is a clear dependency betweeen libraries?

2. If the libraries are not important, that is, the subdirectory is purely for the sake of ordering files in a clear way, should we change the STATIC libraries to OBJECT libraries, such as  (add_library(celestia STATIC ${CELESTIA_SOURCES}))  ->  (add_library(celestia OBJECT ${CELESTIA_SOURCES})). Then it is clear that it is not an independent library and we can ignore the linking until the final stage.

I have tested a little bit on this two approaches and they both should work, but I am not familiar with the design philosophy of celestia so I would like to hear more about that.

**Comment by pirogronian** [comment]
@dlshcbmuipmam Probably You're right. We just follow maintaining structure created by earlier programmers. I see no reason for maintaining separated modules such a celengine and celestia. I'd rathet divide the code into, for example, render/, input/, lua/, core/, etc. Celmath, celutil and others small modules seens to have more clear deps. But our changes are slow due to lack of human power :-)

**Comment by dlshcbmuipmam** [comment]
@pirogronian This summarizes the dependencies:
cel3ds: celutil
celengine: cel3ds, celephem, celestia, celmath, celmodel, celtxf, celutil
celephem: celengine, celmath, celutil
celestia: celengine, celephem, celmath, celtxf, celutil
celmath:
celmodel: celutil
celtxf: celutil
celutil: celmath

As you can see, celengine, celephem, celestia mess up with each other. 

A simple fix would be grouping celengine, celephem, celestia in to a single celengine, delete celephem, and remain celestia for all the different gui. I can work on this if you guys agree, further dividing into render/, input/, lua/, core/, etc. is beyond my current understanding of the code.

**Comment by pirogronian** [comment]
@dlshcbmuipmam You always can post a pull request, however due to massive files relocations I would wait for @375gnu opinion.

**Comment by 375gnu** [comment]
Basically agree.

Actually only one thing in celengine/ depends on celestia/: legacy scripting, I thought that we should move it to celestia/ subdir.

Celephem/ technically is a part of celengine/, on the other hand it depends on astro utilities and parser, both can be moved to their own libs. It also depends on body.h but I hope once we will remove this code :)

Our CMakeLists.txt contain traces of my experiments with shared libraries, actually they were abandoned because of other issues, mostly with removal of global objects. I'd like to have shared libraries used by different frontends and tools, but actually we don't need every dir to be a so/dll.

I'd say that subdirectories are used in src/ to logically group files by their functions. But still celengine and celestia are total mess.

As a first step we can move command.* and cmdparser.* to celestia and make our "libraries' OBJECTs.
