### ISSUE TITLE
Audio support for CEL/CELX scripts

### ISSUE THREAD

**Issue by CelestiaProject** [CelestiaProject/Celestia#6]
**Celestia-ED-1.6.1** contains the scripts with audio playback. Used **OpenAL** library. 
I believe that to add audio playback for scripts in Celestia 1.7.0 is a good idea. But OpenAL library is outdated and need to use another.

**Comment by Alexell** [comment]
Maybe **FMOD Ex** library?

**Comment by Alexell** [comment]
FMOD Ex will be added.

**Comment by Alexell** [comment]
Original patch created by Victor (vhpgomes), modified by Vincent,
modified and adapted for **FMOD library** by Alexell.
Done:  [37ed932](https://github.com/CelestiaProject/Celestia/commit/37ed932d37efe5c4d4d6650cf8ed37ad6a251122)

**Comment by CelestiaProject** [comment]
Need additional testing and code analysis, because celestia.exe sometimes crash, and source code compilation is not always successful.

**Comment by Alexell** [comment]
Added lost classes in command.cpp
CELX method work correctly.
CEL method error (need to fix).

**Comment by CelestiaProject** [comment]
Need additional testing, because celestia.exe and celestia qt.exe sometimes crashes with **fmod.dll exception**

**Comment by CelestiaProject** [comment]
Need help to fix FMOD support to work properly on Win32, Win64, QT, Linux, MacOS.

**Comment by CelestiaProject** [comment]
@dbrant, we need help to fix FMOD support to work properly on Win32, Win64, QT, Linux, MacOS.

**Comment by dbrant** [comment]
I have a couple of concerns about the choice to use FMOD instead of OpenAL, specifically when building for Linux:
- I'm not familiar with FMOD, but it looks like it's a commercial (closed-source) library. Because of this, it's not available in any package manager of any Linux distribution. Therefore, if a volunteer (like me) wants to start contributing, they would need to manually go to the fmod website, download the libraries (which requires creating an account!), and manually copy the libraries and headers to /usr/local/. That's quite a few steps, and easily enough to turn someone away from contributing.
- More importantly, since FMOD is closed-source, will it prevent Celestia from being included in the package managers of Linux distros (i.e. allow users to install it with `apt-get install celestia`)? Again, I'm not familiar with the licensing and distribution agreements of FMOD, but I doubt that Ubuntu or Fedora would agree to distribute Celestia if it starts linking to a closed-source library.

**Comment by CelestiaProject** [comment]
@dbrant, The FMOD website says "Free for small teams".

I wrote a letter for FMOD asking for permission to use FMOD in Celestia. Permission was given, we can use FMOD under the [EULA license](https://www.fmod.org/eula/).
It is written there:
> FMOD is distributed as integrated into a Product only
As I understand it, it suits us.

Of course I have an account to download the FMOD libraries (I can send you archives of the library, for example to the email). 
Maybe you're right about the possible problem with package managers of Linux distros.
If you think that FMOD is wrong to use in the open-source project, we are ready to listen to your suggestions.

**Comment by nisselarsson** [comment]
FMOD support is guarded with _WIN32 ifdefs now.

**Comment by CelestiaProject** [comment]
It is necessary to use QT Audio.

**Comment by CelestiaProject** [comment]
@pirogronian Channel is the definition of FMOD. But this is not left, right, or center. For this, there is pan. FMOD must be completely removed from the Celestia code. The new version of Celestia will be built **only with QT**. And QT has built-in audio support (**QT Audio**). Please try to understand how it works and include it.

**Comment by pirogronian** [comment]
@CelestiaProject Qt Audio doesn't have pan support. On the other side, OpenAL is designed to be fully 3D. I don't know if it's outdate or not, but its api looks most usefull from all I have seen working on sound in Celestia.

**Comment by CelestiaProject** [comment]
@pirogronian In general, we do not need PAN support. Although sometimes in scenarios, using panning sound would be interesting. Should we include a third-party library for PAN support?
Let's discuss. In what way can you support audio in mp3 and wav formats (at least the basic commands: play, pause, stop, volume, loop)?

**Comment by pirogronian** [comment]
For simple layback, Qt will be completely suffcient, I think. And I can implement it with script interface almost identical to this, desgned for FMOD.

**Comment by CelestiaProject** [comment]
@pirogronian Please do it.
To start, please completely remove the FMOD includes from the source code, then replace the parts of the code that cause the FMOD to play audio to the code for QT. All the changes made earlier for audio playback you can see in this commit: https://github.com/CelestiaProject/Celestia/commit/37ed932d37efe5c4d4d6650cf8ed37ad6a251122
Please, after the playback through QT is ready, check that Celestia is successfully compiled, and also check the correctness work of the demo scripts from the **scripts/audio** folder.
When everything is checked and it will work normally, we wait for your **pull request**.

P.S. If you have ideas for future changes in Celestia in the future, we can add you to the **contributors** so that you can make changes to the repository directly, without pull request.

**Comment by Alexell** [comment]
@pirogronian Celestia code with latest changes **compilation failed** with **QT 5.9.2 (release MSVC2015 32bit/64bit and MinGW 32bit)**.
Swears that identifiers are not found in **celx.cpp**:
```
luaL_newstate
lua_iolibopen
lua_baselibopen
lua_mathlibopen
lua_tablibopen
lua_strlibopen
```
Can you fix it?

**Comment by pirogronian** [comment]
It's probably due to different direction of iteration over lua versions list in celestia.pro. What works on my system,, fail on yours and vice versa. Solution would be rewrite of version detection. However, I have to think on it yet.

**Comment by Alexell** [comment]
@pirogronian Unfortunately, nothing has changed. All the same errors in the **celx.cpp** file
Your changes were in the **unix** section, and I'm talking about compiling Windows x86/x64

**Comment by pirogronian** [comment]
@Alexell
I don't understand. Lua_ver is set only in unix section, so on Windows
preprocessor condition should activate code for lower versions. However,
without windows I there will be problem to recreate whats going on.

W dniu czwartek, 24 maja 2018 Alexell <notifications@github.com> napisał(a):
> @pirogronian Unfortunately, nothing has changed. All the same errors in
the celx.cpp file
> Your changes were in the unix section, and I'm talking about compiling
Windows x86/x64
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/RosnDDQy0QjoyKnxyV-75NeR9bUpnZcolXd6W4hi4KGBHLOpiPxCyY2kspdu9kv2k8uQ7cZtjmdhs_gF58MxE3rgVbAyPXWhb4E27Xle_w4S-gNxCh5WX7Dc4l3bD0TjHDUj0ilzdiwy_Gk7RDZQJjklJJUglg=s0-d-e1-ft#https://github.com/notifications/beacon/AI2gODQnRjffbNFuA2rv9TfGpJT0StYGks5t1nnPgaJpZM4L1Gc4.gif>

**Comment by pirogronian** [comment]
My story is following: once I pulled changes to prepare playback commit, compilation blew up with the same errors, as @Alexell mentioned. I discovered this lua version detection loop in unix section of celestia.pro and reverted list, which fixed problem. So, when AlexelI posted about the issue, I though it's due my reverted list. But in this situation it's probably related to this [commit](https://github.com/CelestiaProject/Celestia/commit/6c910e583efd5da6f3821c58fcf9eef8ccdef52c) by @375gnu. Based on my experiences, this is probably due to wrong LUA_VER macro value on win32/64.

**Comment by Alexell** [comment]
@pirogronian Yes, these were the errors of luaL_newstate and other identifiers that I pointed out. Now at compilation of these errors already is not present, but there are others, concerning QtAudioManager. If I can not fix them, I'll write about it.

**Comment by Alexell** [comment]
@pirogronian You implemented audio playback only for **.celx** scripts. My commit has fix code for the correct work of **.cel** scripts.
**But there was one problem:** in .cel or .celx scripts on Windows audio playback **does not work**. The script runs fine, no errors occur (including in the console), but audio files are not played.
In addition, the construct `fpath.cd (CONFIG_DATA_DIR);` does not work for Windows, because `CONFIG_DATA_DIR` is not declared.

**I performed a successful compilation using two different code options:**
```
    if (QDir::isRelativePath(fn)) {
        QDir fpath = QDir::current();
        fpath.cd("sounds");
        //if (!fpath.exists(fn)) { fpath.cd(CONFIG_DATA_DIR); fpath.cd("sounds"); }
        if (!fpath.exists(fn)) {
            cout << "Cannot play \'" << fn.toUtf8().data() << "\'No file found.\n";
            return;
        }
        QUrl url = QUrl::fromLocalFile(fpath.filePath(fn));
        path = url.url(QUrl::NormalizePathSegments);
    } else {
        QUrl url = QUrl::fromLocalFile(fn);
        path = url.url(QUrl::NormalizePathSegments);
    }
```
and
```
    if (QDir::isRelativePath(fn)) {
        QDir fpath = QCoreApplication::applicationDirPath();
        fpath.cd("sounds");
        if (!fpath.exists(fn)) {
            cout << "Cannot play \'" << fn.toUtf8().data() << "\'No file found.\n";
            return;
        }
        QUrl url = QUrl::fromLocalFile(fpath.filePath(fn));
        path = url.url(QUrl::NormalizePathSegments);
    } else {
        QUrl url = QUrl::fromLocalFile(fn);
        path = url.url(QUrl::NormalizePathSegments);
    }
```

**But in both cases, audio is not played.** It's strange that if you delete audio files from **sounds** folder, the cel/celx script executes and **does not show any errors**, although it should show **No file found**.
Do you have audio playback on Linux?
Let's try to fix this for Windows.

**Comment by pirogronian** [comment]
Yes,on Linux playback is brilliant. Tested many times. However I just
noticed lack of error message code in case of path being absolute.

W dniu poniedziałek, 28 maja 2018 Alexell <notifications@github.com>
napisał(a):
> @pirogronian You implemented audio playback only for .celx scripts. My
commit has fix code for the correct work of .cel scripts.
> But there was one problem: in .cel or .celx scripts on Windows audio
playback does not work. The script runs fine, no errors occur (including in
the console), but audio files are not played.
> In addition, the construct fpath.cd (CONFIG_DATA_DIR); does not work for
Windows, because CONFIG_DATA_DIR is not declared.
>
> I performed a successful compilation using two different code options:
>
> if (QDir::isRelativePath(fn)) {
> QDir fpath = QDir::current();
> fpath.cd("sounds");
> //if (!fpath.exists(fn)) { fpath.cd(CONFIG_DATA_DIR); fpath.cd("sounds");
}
> if (!fpath.exists(fn)) {
> cout << "Cannot play \'" << fn.toUtf8().data() << "\'No file found.\n";
> return;
> }
> QUrl url = QUrl::fromLocalFile(fpath.filePath(fn));
> path = url.url(QUrl::NormalizePathSegments);
> } else {
> QUrl url = QUrl::fromLocalFile(fn);
> path = url.url(QUrl::NormalizePathSegments);
> }
>
> and
>
> if (QDir::isRelativePath(fn)) {
> QDir fpath = QCoreApplication::applicationDirPath();
> fpath.cd("sounds");
> if (!fpath.exists(fn)) {
> cout << "Cannot play \'" << fn.toUtf8().data() << "\'No file found.\n";
> return;
> }
> QUrl url = QUrl::fromLocalFile(fpath.filePath(fn));
> path = url.url(QUrl::NormalizePathSegments);
> } else {
> QUrl url = QUrl::fromLocalFile(fn);
> path = url.url(QUrl::NormalizePathSegments);
> }
>
> But in both cases, audio is not played. It's strange that if you delete
audio files from sounds folder, the cel/celx script executes and does not
show any errors, although it should show No file found.
> Do you have audio playback on Linux?
> Let's try to fix this for Windows.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/yyNUgknVc4c0a1W6LxKZ9_gmbS4hwSufMTjUHyuTysvE5QeyO2eKXK9AVvtgvrDYtkEtblyRI17rUAAtZCUr1kG5I7Y90yCoUnLv890Fxl0U6ry8KCGFL4euolt4yr1QLsNnuArGsJjZDXP6je8eMtanm0__2Q=s0-d-e1-ft#https://github.com/notifications/beacon/AI2gOFaswa8szDm1JzxsUbuGo_Jiyabtks5t29dvgaJpZM4L1Gc4.gif>

**Comment by pirogronian** [comment]
In fact, I didn't forget about *.cel, just didn't know what it is and where is its code. Additionally, errors throwed by cel scritps were without any description.
When I tested nopause parameter, setting it to false caused stopping playback after pressing space. Will check it again, probably tomorrow. Thanks for response.

**Comment by pirogronian** [comment]
Just checked. Celx script works with audio, however, indeed, nopause parameter don't work. Cel script has no audio and no console output.
(Celx debug output, I forgot to remove it before submit PR):
>playAudioFile(0, 1, 1, music.mp3, 1)
>playAudioFile(1, 1, 0, comment.mp3, 0)
>playAudioFile(0, 0.8, 0, -, 0)
>playAudioFile(0, 0.6, 0, -, 0)
>playAudioFile(0, 0.4, 0, -, 0)
>playAudioFile(0, 0.2, 0, -, 0)
>playAudioFile(0, 0.1, 0, -, 0)
>playAudioFile(0, -1, 0, , 0)
>playAudioFile(1, -1, 0, , 0)
Where to look for Cel script operation code?

**Comment by Alexell** [comment]
@pirogronian On Windows the sound works, I wrote earlier. At first it did not work, because there were not enough dlls.

**Comment by pirogronian** [comment]
@Alexell indeed, I confused "now" with "no"... So, when my pause fix will be commited, will this issue finally closed?

**Comment by Alexell** [comment]
@pirogronian After PR merge, I'll also check **loop** and **nopause** parameters conformity for the description, which is written for them in demo scripts.

**Comment by Alexell** [comment]
Everything is working.
