### ISSUE TITLE
Garbled list box in Chinese environment

### ISSUE THREAD

**Issue by Skystars-NH** [CelestiaProject/Celestia#622]
Garbled list box in Chinese environment.
OS: Windows
Version:1.6.2 beta2

**Comment by eyvallah** [comment]
> Garbled list box in Chinese environment.
> OS: Windows
> Version:1.6.2 beta2

can you please attach a screenshot?

**Comment by Skystars-NH** [comment]
![screenshot](https://user-images.githubusercontent.com/58061215/75103085-b7c85580-5630-11ea-8702-5439a9939c55.png)

**Comment by Skystars-NH** [comment]
Is there a 32-bit version of Celestia?

**Comment by Skystars-NH** [comment]
Could Celestia be added with flare selection?

**Comment by eyvallah** [comment]
im afraid no one in this team has a Chinese development Windows machine, but I think the text on the table header should be values from .po, aren't they? @375gnu

**Comment by hv-work** [comment]
@eyvallah correct. This line https://github.com/CelestiaProject/Celestia/blob/1.6.x/src/celestia/wineclipses.cpp#L57 doesn't work, but only for zh_CN, I suppose the problem is in bundled libiconv, as this code works as expected for my language. Possibly libiconv doesn't support ASCII codepage used in windows.

**Comment by 375gnu** [comment]
I was testing it with `LANGUAGE` that's why I had incorrect output as with `LANGUAGE` one still has CP as defined for the main language, in my case it was CP1251. I have tested 1.6.2 beta2 under wine and `LANG=zh_CN` so CP was CP936 aka GB2312. In this case everything was fine.

@Skystars-NH please ensure that you use beta2 and not beta1.

**Comment by SevenSpheres** [comment]
I just tested 1.6.2-beta2 using `set LC_MESSAGES=zh_CN` and I see the same thing as @Skystars-NH.

**Comment by 375gnu** [comment]
@Skystars-NH what your setting are for non-Unicode applications?

**Comment by eyvallah** [comment]
this can be solved by adding this line 
```
    CONTROL         "", -1, WC_NATIVEFONTCTL, NFS_ALL, 0, 0, 0, 0
```
to the dialogs.
