### ISSUE TITLE
fractional part of julian date can't be edited correct in Qt

### ISSUE THREAD

**Issue by GottfriedSp** [CelestiaProject/Celestia#76]
The fractional part cant be edited.
Example: when removing the fractional part and then set the value 2452251,**2** it is automatic filled with 2452251,2000000002 and cant be edited from this point

**Comment by 375gnu** [comment]
This is due to how floating point numbers are implemented in hardware, we can't fix it.

**Comment by GottfriedSp** [comment]
Possible implementation is not to change the time and date during editing julian date.
When QLineEdit lost its focus, it can calculate the date and time which also updated the juliandate.

**Comment by ajtribick** [comment]
Editing should be fixed now since the update signals are no longer being bounced back-and-forth between the time component boxes and the JD entry, and the controls in question now use spinboxes rather than line edits.

The values still get adjusted to something slightly off, might be worth reducing the number of decimal places to, e.g. 6 (which still gives ~1/10 second precision)
