### ISSUE TITLE
Add CJK ttf fonts

### ISSUE THREAD

**Issue by levinli303** [CelestiaProject/Celestia#761]
**Is your feature request related to a problem? Please describe.**
DejaVuSans does not include CJK characters

**Describe the solution you'd like**
Add CJK ttf fonts, also standardize the filename for fonts so they can be picked up easily

**Additional context**
Simplified/Traditional Chinese seems to use WenQuanYi in .txf fonts

**Comment by eyvallah** [comment]
So after implementing using system font to display function on mobile oses, I still find it hard to make it work well for all languages.

For example, I had a feedback from a Samsung user where Hanguls display well but latin characters do not. After investigation, Samsung phone uses SamsungKorean-Regular as the default font to render Hanguls, and only consists Hangul glyphs. The system fallback to other fonts for latin characters and etc. This is also true with Arabic on iPhone where the default font for Arabic only contains Arabic letters but not latin characters and etc.

So to ensure that we are not seeing most characters displayed as tofu, probably we might
1. supporting multiple font for displaying by specifying unicode range? or just fallback when a glyph is not found.
2. or just provide more fonts (I suppose we can use Noto fonts here, basically we just need to get the main one for latin/cyril characters, and CJK one for CJK, Arabic is still kinda tricky since NotoSansArabic does not contain latin glyphs either)

**Comment by 375gnu** [comment]
>     1. supporting multiple font for displaying by specifying unicode range? or just using fallback when a glyph is not found.

I prefer the 2nd variant. It's simpler to implement and doesn't limit users when they want to use their preferred fonts.

In emacs editor you can create a "fontset" with several fonts, I think we can provide something similar.

Actually, we can also provide unicode range in font definition in config file.

**Comment by 375gnu** [comment]
And we don't support RTL scripts yet.

**Comment by joequant** [comment]
Would it be possible to pull in system fonts?  That would make things a lot easier.

**Comment by 375gnu** [comment]
That's what @levinli303 tries to implement in mobile frontends.

**Comment by levinli303** [comment]
> Would it be possible to pull in system fonts? That would make things a lot easier.

there are two blockers

1. a system font can still lack common characters. see the example I posted where a system font for Korean on Samsung phone does not contain latin characters. Then we need to have a fallback system like an OS
2. Different OS have different APIs for finding default system font, Mac/iOS uses CTFont, Android uses its XML, Windows uses DirectWrite. We would need to write a lot of compat layer to support it directly in Celestia, so I'm now doing it on mobile front ends but might be shifting away from it for now, until font fallback can be achieved.

**Comment by joequant** [comment]
What I was thinking was to not necessary use the system font interfaces but
to use the system font files
since most systems have a ttf file stuck somewhere.

**Comment by joequant** [comment]
Also until we have CJK fonts working, can we at least have TXF fonts as a
fallback which can be optionally
compiled in?  I'm packaging celestia for mageia linux and I can't package
the most recent version since TXF
is completely disabled and CJK won't work.

>

**Comment by levinli303** [comment]
@joequant you can set font in celestia.cfg, system font will work if you supply the full path.

**Comment by joequant** [comment]
Cool!!!  That fixes the problem for me since I can package it with system
fonts.

I've found that the google-noto-sans-cjk-ttc have all of the unicode fonts
for cjk.

**Comment by 375gnu** [comment]
Hi @joequant , thank you for Mageia packages. I see that Mageia still supports 1.6.1, so please apply this commit e477a22d to fix scripted orbits and rotations. Also for 1.7 i would suggest to use luajit instead of plain lua.

**Comment by joequant** [comment]
I'm focusing on mageia 8 which has the latest git verison of celesita.
Will use luajit thanks for the ping.

**Comment by levinli303** [comment]
Closing, I think its a better idea to not bundle extra fonts in this repo at the moment, it will increase size greatly. Just edit celestia.cfg to use a system font or a custom font that user downloads
