### ISSUE TITLE
Bump required C++ version to C++17

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#919]
I don't think that when we release Celestia 1.7 it will be hard to find a system with C++17 support. Ubuntu 16.04 is near it's EOL, 18.04 ships both g++7 and g++8. Debian stable has g++8. Windows users can install VS2019 or mingw-g++ 8. Also LLVM project provides builds for different systems. I don't know how it's supported on macOS/iOS and Android.

But C++17 has a lot of useful features, especially `std::filesystem` so we can drop own implementation and `std::sting_view` which can speedup text files parsing, see `celengine/hash.cpp`.

So @levinli303 what do you think?

**Comment by levinli303** [comment]
I agree we should bump c++ version to 17. one benefit would be https://eigen.tuxfamily.org/dox-devel/group__TopicStlContainers.html so we don't have to handle some issues about alignments in eigen3. The latest iOS/Mac/Android releases on AppStore/GooglePlay are already built with C++17.

However we cannot drop our implementation of filesystem on iOS/Mac since std::filesystem on iOS/Mac also has system version requirement (iOS 13/macOS 10.15) and currently the releases target iOS 11/macOS 10.10. On Android the latest NDK 22 has std::filesystem, I've not used it yet, but it should not have system version requirements.

**Comment by 375gnu** [comment]
Is it possible to link statically or ship custom `libc++.so` with an application?

**Comment by levinli303** [comment]
Apple didn't give us static libc++ so we'll have to compile our own version of libc++ from llvm code. and I am not sure if this will play well with the toolchain or pass the app review. but I assume it is possible to at least build it with a libc++ static, since Chromium did it to support macOS 10.6 until 2016.

another way is just to bump macOS deployment target to macOS 10.14 (released in 2018), current iOS target (iOS 11) has aligned deallocation, we still cannot use filesystem tho.

**Comment by levinli303** [comment]
let's do this when iOS 15/macOS 12 are released, so we will be supporting 3 major versions. (iOS 13, 14, 15, macOS 10.15, 11.0, 12.0)

**Comment by ajtribick** [comment]
In the meantime, would it make sense to bump the C++ version to C++14, as this has much stronger support and provides several quality-of-life improvements already? I see that catch.hpp in the tests directory is already using `std::make_unique`, so perhaps the test suite already requires this?

**Comment by 375gnu** [comment]
c++14 simplifies life a little bit: relaxed `constexpr` functions, `auto` in lambdas, `std::make_unique`. so i'm in favor of such bump.

**Comment by levinli303** [comment]
it should be good to bump it, I believe the macOS libc++ supports c++14 a long time ago.

**Comment by ajtribick** [comment]
Since iOS 15 and macOS 12 have been released, do we want to take another look at this?

**Comment by levinli303** [comment]
> Since iOS 15 and macOS 12 have been released, do we want to take another look at this?

Yeah I think we are good to do it now. Can you take it?

**Comment by ajtribick** [comment]
Yes, I would be able to do it, if @375gnu is also happy to go ahead with C++17?

**Comment by 375gnu** [comment]
I'm not happy, I'm excited with this :) Let's go!
